version: '3.8'

services:
  vg-ms-inventory-purchases:
    build: .
    container_name: vg-ms-inventory-purchases
    ports:
      - "8088:8088"
    environment:
      - SERVER_PORT=8088
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/JASS_INVENTORY
    depends_on:
      - mongo
    networks:
      - jass-network

  mongo:
    image: mongo:latest
    container_name: mongo-inventory
    ports:
      - "27018:27017" # Port mapped to 27018 to avoid conflict if running simultaneously with users
    volumes:
      - mongo_data_inventory:/data/db
    networks:
      - jass-network

networks:
  jass-network:
    driver: bridge

volumes:
  mongo_data_inventory:
