spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/notification_db_dev

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  mail:
    enabled: false  # Deshabilitado en desarrollo para evitar env√≠os reales
    host: smtp.gmail.com
    port: 587

whatsapp:
  api:
    url: http://localhost:3001
    enabled: false  # Deshabilitado en desarrollo

sms:
  gateway:
    url: http://localhost:3002
    enabled: false  # Deshabilitado en desarrollo

logging:
  level:
    root: DEBUG
    pe.edu.vallegrande.vgmsnotification: TRACE
    org.springframework.data.mongodb: TRACE
