version: '3.8'

services:
  vg-ms-authentication:
    build: .
    container_name: vg-ms-authentication
    ports:
      - "9092:9092"
    environment:
      - SERVER_PORT=9092
      - KEYCLOAK_REALM=sistema-jass
      - KEYCLOAK_CLIENT_ID=jass-auth-service
      - MS_USERS_URL=https://genetic-yolane-vallegrandesistema-a92b57a3.koyeb.app/api
    networks:
      - jass-network

networks:
  jass-network:
    driver: bridge
