version: '3.8'

services:
  app:
    build: .
    container_name: vg-ms-organizations
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - MONGODB_URI=mongodb://mongo:27017/JASS_DIGITAL
      - JWT_ISSUER_URI=https://lab.vallegrande.edu.pe/jass/keycloak/realms/sistema-jass
      - JWT_JWK_SET_URI=https://lab.vallegrande.edu.pe/jass/keycloak/realms/sistema-jass/protocol/openid-connect/certs
      - MS_USERS_URL=https://lab.vallegrande.edu.pe/jass/ms-users
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    depends_on:
      - mongo
    networks:
      - jass-network

  mongo:
    image: mongo:6.0
    container_name: jass-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=JASS_DIGITAL
    volumes:
      - mongo-data:/data/db
    networks:
      - jass-network

networks:
  jass-network:
    driver: bridge

volumes:
  mongo-data:
