version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: vg-organizations-mongo
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: JASS_DIGITAL
    volumes:
      - mongodb_data:/data/db
    networks:
      - vg-network

  vg-ms-organizations:
    build: .
    container_name: vg-ms-organizations
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      MONGODB_URI: mongodb://mongodb:27017/JASS_DIGITAL
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      USER_SERVICE_URL: http://vg-ms-users:8081
    depends_on:
      - mongodb
    networks:
      - vg-network

volumes:
  mongodb_data:

networks:
  vg-network:
    external: true
