spring:
  application:
    name: vg-ms-inventory-purchases
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  port: ${SERVER_PORT:8088}

# Configuraci√≥n de logging
logging:
  level:
    root: INFO
    pe.edu.vallegrande: DEBUG

