version: '3.8'

services:
  vg-ms-users:
    build: .
    container_name: vg-ms-users
    ports:
      - "8085:8085"
    environment:
      - SERVER_PORT=8085
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/JASS_DIGITAL
      - KEYCLOAK_ISSUER_URI=https://lab.vallegrande.edu.pe/jass/keycloak/realms/sistema-jass
      - KEYCLOAK_JWK_SET_URI=https://lab.vallegrande.edu.pe/jass/keycloak/realms/sistema-jass/protocol/openid-connect/certs
    depends_on:
      - mongo
    networks:
      - jass-network

  mongo:
    image: mongo:latest
    container_name: mongo-users
    ports:
      - "27017:27017"
    volumes:
      - mongo_data_users:/data/db
    networks:
      - jass-network

networks:
  jass-network:
    driver: bridge

volumes:
  mongo_data_users:
