version: '3.8'

services:
  postgres-users:
    image: postgres:16-alpine
    container_name: postgres-users
    environment:
      POSTGRES_DB: vg_users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-users-data:/var/lib/postgresql/data
    networks:
      - jass-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  vg-ms-users:
    build: .
    container_name: vg-ms-users
    environment:
      SPRING_PROFILE: prod
      PORT: 8081
      DB_HOST: postgres-users
      DB_PORT: 5432
      DB_NAME: vg_users
      DB_USER: postgres
      DB_PASSWORD: postgres
      RABBITMQ_HOST: genetic-yolane-vallegrandesistema-a92b57a3.koyeb.app
      RABBITMQ_PORT: 443
      RABBITMQ_USER: admin
      RABBITMQ_PASSWORD: admin
    ports:
      - "8081:8081"
    depends_on:
      postgres-users:
        condition: service_healthy
    networks:
      - jass-network
    restart: unless-stopped

volumes:
  postgres-users-data:

networks:
  jass-network:
    driver: bridge
