version: '3.8'

services:
  ms-distribution:
    image: isaelfatamadev/jass-ms-distribution:latest
    container_name: ms-distribution
    
    ports:
      - "${PORT:-8086}:8086"
    
    # Carga todas las variables de entorno desde .env
    env_file:
      - .env
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/jass/ms-distribution/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    networks:
      - jass-network
    
    deploy:
      resources:
        limits:
          memory: 250M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'

networks:
  jass-network:
    driver: bridge
